# -*- coding: utf-8 -*-
"""PDFdeleter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zH8pr1C2DOb9eTVaFDV9Fv1CtCG-Cpyc
"""

pip install PyPDF2

import PyPDF2
from PyPDF2 import PdfWriter, PdfReader

"""Steps:
1) upload pdf of slides to colab

2) copy the file path of the slides to the area below next to "mypdf = open(", make sure to not delete the ",rb)"

3) Change the output file name next to "with open(" at bottom. Make sure to include .pdf after the name you want.

4) Download the pdf with the name you chose from colab. You are done.

*note: only work if page number is x / y as the last thing on the slides, if not will not read the "x" properly and have to change code a bit
"""

#creating a pdf file object
#------------------------------------------------------------------------------------
mypdf = open("/content/PBE once again.pdf", 'rb') #ENTER PDF FILE PATH TO BE READ HERE
#------------------------------------------------------------------------------------
# creating a pdf reader object
reader = PyPDF2.PdfReader(mypdf)

parts=[]
numbarray = []
def visitor_body(text, cm, tm, fontDict, fontSize):
    y = tm[5]
    if y < 50:
        parts.append(text)



#make list of all pages
for i in range(len(reader.pages)):
  page = reader.pages[i]
  page.extract_text(visitor_text=visitor_body)
  text_body = "".join(parts)
  pagenumbs = text_body.split()
  pagenumber = pagenumbs[-3] #note this is what to change if slide number is different format
  #print(pagenumber)
  numbarray.append(pagenumber)


writer = PdfWriter() #defines a pdf to write in

#adds greatest nonrepetitive page to writer
numbskip=99999999999
for i in range(len(numbarray)):
  if numbskip == numbarray[i]:
    #dont go through, alredy got the greatest
    continue
  else:
    for j in range(len(numbarray)):
      if numbarray[i] == numbarray[len(numbarray)-j-1]:
        numbskip = numbarray[len(numbarray)-j-1]
        writer.add_page(reader.pages[len(numbarray)-j-1])
        break
      else:
        continue
    #go through for loop again, check for next lowest number


#NAME THE DOCUMENT HERE
#------------------------------------------------------------------------------------
with open("PBE once again.pdf", "wb") as fp:
#------------------------------------------------------------------------------------
    writer.write(fp)

# closing the pdf file object
mypdf.close()